language: python
python: 2.7
env:
  - TOXENV=py27
  - TOXENV=pypy
  - TOXENV=pre-commit
  - TOXENV=docs
  - TOXENV=lint
cache: pip
matrix:
  fast_finish: true
install:
  - pip install tox
script:
  - tox -e $TOXENV
after_success:
  - curl -Lo travis_after_all.py https://git.io/travis_after_all
  - python travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          python setup.py coverage && codecov
        fi
      fi
