language: python
cache: pip
matrix:
  include:
  - python: '2.7'
    env: TOXENV=py27
  - python: '2.7'
    env: TOXENV=pre-commit
  - python: '2.7'
    env: TOXENV=docs
  - python: '2.7'
    env: TOXENV=lint
  fast_finish: true
install:
  - pip install tox
script:
  - tox -e $TOXENV
